---
abstract: 'Interface to access the http API on RabbitMQ Brokers'
author:
  - 'Shane Utt (shane@shaneutt.com)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-RabbitMQ-Broker
no_index:
  directory:
    - t
    - inc
requires:
  Test::Simple: 0.44
version: 0.01
